# Generated by Django 5.2.11 on 2026-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_team_lead_team_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("AGENT", "Agent"), ("TEAM_LEAD", "Team_Lead")], max_length=20
            ),
        ),
    ]
