# Generated by Django 5.2.11 on 2026-04-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="team",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
