# Generated by Django 5.2.12 on 2026-04-06 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('priority', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('is_active_ticket', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
