# Generated by Django 5.2.11 on 2026-04-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In_Progress"),
                    ("RESOLVED", "Resolved"),
                    ("PENDING", "Pending"),
                    ("PARKED", "Parked"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
